### ISSUE TITLE
[!] The 'Pods-Kiosk' target has frameworks with conflicting names: artsy_uifonts.

### ISSUE THREAD

**Issue by xwgit2971** [artsy/eidolon#667] opened 2017-07-04 08:54 UTC
[!] The 'Pods-Kiosk' target has frameworks with conflicting names: artsy_uifonts.

+------+-----------------------+-------------+
|              fastlane summary              |
+------+-----------------------+-------------+
| Step | Action                | Time (in s) |
+------+-----------------------+-------------+
| 1    | Verifying required    | 0           |
|      | fastlane version      |             |
| 2    | Switch to oss_keys    | 0           |
|      | lane                  |             |
| 3    | cd .. ; bundle exec   | 11          |
|      | pod keys set          |             |
|      | ArtsyAPIClientSecret  |             |
|      | '-' Eid               |             |
| 💥   | cocoapods             | 2364        |
+------+-----------------------+-------------+

[16:51:34]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

**Comment by ashfurrow** [comment] 2017-07-05 14:46
Hey there – this appears to be a duplicate of the problem in #636. I'm hoping to figure this out today. In the mean time, please follow that issue for updates. Thanks for opening an issue 🙇

**Closed by ashfurrow** 2017-07-05 14:46 UTC
